exp:
  model_id: "PatchTSTBlind"
  seed_list: [69421, 69422, 69423, 69424, 69425]
  learning_type: "sl"
  scale: True
  balance: True
  acc: True
  ch_acc: False
  other_metrics: True
  batchwise_metrics: True
  rank_verbose: False
  best_model_metric: "ch_acc"
  tuning_metric: "ch_f1"
  task: "classification"
  gpu_id: 0
  neptune: False

data:
  full_channels: True
  resizing_mode: "pad_trunc"
  seq_load: True
  dataset: "open_neuro"
  seq_len: 10000
  pred_len: 1 # 1 if binary classification, 'n' for n-class classification
  num_channels: 1
  train_split: 0.7
  val_split: 0.1
  num_workers: 4
  scale: True
  shuffle_test: True
  dtype: "float32"
  median_seq_len: False

ddp:
  ddp: False
  master_port: "11359"

scheduler:
  T_max: 50

sl:
  optimizer: "adam"
  criterion: "BCE"
  scheduler: "cosine"
  epochs: 50
  batch_size: 4096
  lr: 1e-5
  num_enc_layers: 1
  d_model: 32
  d_ff: 32
  num_heads: 4
  attn_dropout: 0.3
  ff_dropout: 0.3
  pred_dropout: 0.0
  early_stopping: True
  weight_decay: 1e-4
  revin: True
  revin_affine: True
  revout: False
  dataset_class: "classification"
  head_type: "linear"

open_neuro:
  patient_cluster: "all"
  kernel_size: 24
  kernel_stride: -1
  task: "binary"
  all_clusters: True
  loocv: False
  train_clusters: ["pt", "umf", "ummc"]
  test_clusters: ["jh"]

early_stopping:
  patience: 15
